#
# SITE SETTINGS 
#

# GENERAL
url: 

include: ["_pages"]

# SASS
sass: 
  sass_dir: ./_scss
  style: compressed

collections:
  products:
    output: true
    permalink: "/product/:title/"

# DEFAULT SETTINGS PER PATH OR TYPE
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"