#
# SITE SETTINGS 
#

# GENERAL
url: /polymorphcrafts/public
destination: public

# COMPILATION
include: ["_pages", ".htaccess"]

# SASS
sass: 
  sass_dir: ./_scss
  style: compressed

# COLLECTIONS
collections:
  products:
    output: true
    permalink: "/product/:title/"

# DEFAULT SETTINGS PER PATH OR TYPE
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"