backend:
  name: github
  repo: polymorphcrafts/polymorphcrafts.github.io # Path to your Github repository
  branch: master # Branch to update
  site_domain: polymorphcrafts.netlify.com

media_folder: "assets/images"

collections:
  - name: products
    label: Products
    folder: "_products"
    create: true
    slug: {{slug}}
    fields:
      - {label: Name, name: name , widget: string}
      - {label: Featured Image, name: featured_image, widget: image}
      - {label: Body, name: body, widget: markdown}
      - {label: Retail, name: retail, widget: number}
      - {label: Sale, name: sale, widget: number, required: false}
      - name: customization
        label: Customization
        required: false
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Surcharge, name: surcharge, widget: number}
      - name: addons
        label: addons
        required: false
        widget: list
        fields:
          - name: product
            label: Product
            widget: relation
            collection: products
            searchFields: [name]
            valueField: name